name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: echo "No build step required"

      - name: Deploy to GitHub Pages
        env:
          GIT_SSH_COMMAND: ssh -i deploy_key -o StrictHostKeyChecking=no
        run: |
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git config --global user.email "loganbwu@example.com"
          git config --global user.name "loganbwu"
          npm install
          echo "No build step required"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages -f
