name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          if [ -f package.json ]; then
            npm install
            if npm run build; then
              echo "Build successful"
              echo "BUILD_DIR=build" >> $GITHUB_ENV
            else
              echo "No build step required"
              echo "BUILD_DIR=." >> $GITHUB_ENV
            fi
          else
            echo "No package.json found, skipping build"
            echo "BUILD_DIR=." >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ env.BUILD_DIR }}
        env:
          BUILD_DIR: ${{ env.BUILD_DIR }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          # folder: ${{ steps.build.outputs.BUILD_DIR }}
